const node = {
  nodes: [
    {
      id: 'node1',
      x: 20,
      y: 50,
      label: '客户\n下单', // 显示在图表中
      text: '客户下单', // 用于切换标题
    },
    {
      id: 'node2',
      x: 100,
      y: 50,
      label: '客服\n确认',
      name: 'abnormal',
      text: '客户确认',
    },
    {
      id: 'node3',
      x: 180,
      y: 50,
      label: '客服\n开单',
      text: '客户开单',
    },
    {
      id: 'node4',
      x: 260,
      y: 50,
      label: '客服\n传送',
      text: '客服传送',
    },
    {
      id: 'node5',
      x: 340,
      y: 50,
      name: 'warning',
      label: '仓库\n发货',
      text: '仓库发货',
    },
    {
      id: 'node6',
      x: 420,
      y: 50,
      label: '客户\n签收',
      text: '客户签收',
    },
    {
      id: 'node7',
      x: 500,
      y: 50,
      label: '客户\n妥投',
      text: '客户妥投',
    },
    {
      id: 'node8',
      x: 180,
      y: 180,
      name: 'abnormal',
      label: '采购\n寻源',
      text: '采购寻源',
    },
    {
      id: 'node9',
      x: 280,
      y: 180,
      name: 'warning',
      label: '采购\n下单',
      text: '采购下单',
    },
    {
      id: 'node10',
      x: 380,
      y: 180,
      name: 'warning',
      label: '供应商\n接单',
      text: '供应商接单',
    },
    {
      id: 'node11',
      x: 500,
      y: 180,
      label: '供应商\n发货',
      text: '供应商发货',
    },
    {
      id: 'node12',
      x: 500,
      y: 400,
      label: '仓库\n入库',
      text: '仓库入库',
    },
    {
      id: 'node13',
      x: 380,
      y: 280,
      label: '换货\n申请',
      text: '换货申请',
    },
    {
      id: 'node14',
      x: 380,
      y: 400,
      label: '换货\n审核',
      text: '换货审核',
      name: 'abnormal',
    },
    {
      id: 'node15',
      x: 500,
      y: 280,
      label: '物流\n签收',
      text: '物流签收',
      name: 'abnormal',
    },
  ],
  edges: [
    {
      id: 'edge1',
      target: 'node2',
      source: 'node1',
      calc: true,
      // color: '#ff0000',
      style: {
        stroke: '#7CD13B', // 节点之间连线的样式
      },
    },
    {
      id: 'edge2',
      target: 'node3',
      source: 'node2',
      calc: true,
      // color: '#00FF00'
    },
    {
      id: 'edge3',
      target: 'node4',
      source: 'node3',
      calc: true,
      // color: '#00FF00'
    },
    {
      id: 'edge4',
      target: 'node5',
      isrunning: true,
      source: 'node4',
      calc: true,
      // color: '#00FF00'
    },
    {
      id: 'edge5',
      target: 'node6',
      source: 'node5',
      color: '#00FF00',
      calc: true,
    },
    {
      id: 'edge6',
      target: 'node7',
      source: 'node6',
      isrunning: true,
      color: '#00FF00',
      calc: true,
    },
    {
      id: 'edge7',
      target: 'node8',
      source: 'node3',
      color: '#00FF00',
      calc: true,
    },
    {
      id: 'edge8',
      target: 'node9',
      source: 'node8',
      color: '#00FF00',
      calc: true,
    },
    {
      id: 'edge9',
      target: 'node10',
      source: 'node9',
      color: '#00FF00',
      isrunning: true,
      calc: true,
    },
    {
      id: 'edge10',
      target: 'node11',
      source: 'node10',
      color: '#00FF00',
      calc: true,
    },
    {
      id: 'edge13',
      target: 'node13',
      source: 'node10',
      color: '#00FF00',
      isrunning: true,
      calc: true,
    },
    {
      id: 'edge14',
      target: 'node14',
      source: 'node13',
      color: '#00FF00',
      isrunning: true,
      calc: true,
    },
    {
      id: 'edge16',
      target: 'node15',
      source: 'node11',
      // color: '#FF0000',
      calc: true,
    },
    {
      id: 'edge17',
      target: 'node12',
      source: 'node15',
      // color: '#FF0000',
      calc: true,
    },
  ],
};
module.exports = node;
