
const node = {
  nodes: [{
    id: 'node1',
    x: 20,
    y: 200,
    "class": "1",
    label: "1"
  }, {
    id: 'node2',
    x: 100,
    y: 200,
    "class": "2",
    "label": "2"
  }, {
    id: 'node3',
    x: 180,
    y: 200,
    "class": "3",
    "label": "3"
  }, {
    id: 'node4',
    x: 260,
    y: 150,
    "class": "4",
    "label": "4"
  }, {
    id: 'node5',
    x: 340,
    y: 150,
    "class": "5",
    "label": "5"
  }, {
    id: 'node6',
    x: 420,
    y: 150,
    "class": "6",
    "label": "6"
  }, {
    id: 'node7',
    x: 500,
    y: 150,
    "class": "7",
    "label": "7"
  }, {
    id: 'node8',
    x: 260,
    y: 250,
    "class": "8",
    "label": "8"
  }, {
    id: 'node9',
    x: 340,
    y: 250,
    "class": "9",
    "label": "9"
  }, {
    id: 'node10',
    x: 420,
    y: 250,
    "class": "10",
    "label": "10"
  }, {
    id: 'node11',
    x: 500,
    y: 250,
    "class": "11",
    "label": "11"
  }, {
    id: 'node12',
    x: 500,
    y: 350,
    "class": "12",
    "label": "12"
  }, {
    id: 'node13',
    x: 420,
    y: 350,
    "class": "13",
    "label": "13"
  }, {
    id: 'node14',
    x: 180,
    y: 350,
    "class": "14",
    "label": "14"
  }],
  edges: [{
    id: 'edge1',
    target: 'node2',
    source: 'node1',
    // color: '#ff0000',
    style: {
      stroke: '#7CD13B', //节点之间连线的样式
    }
  },
  {
    id: 'edge2',
    target: 'node2',
    source: 'node3',
    // color: '#00FF00'
  }, {
    id: 'edge3',
    target: 'node3',
    source: 'node4',
    // color: '#00FF00'
  }, {
    id: 'edge4',
    target: 'node5',
    source: 'node4',
    // color: '#00FF00'
  }, {
    id: 'edge5',
    target: 'node6',
    source: 'node5',
    color: '#00FF00'
  }, {
    id: 'edge6',
    target: 'node7',
    source: 'node6',
    color: '#00FF00'
  }, {
    id: 'edge7',
    target: 'node8',
    source: 'node3',
    color: '#00FF00'
  }, {
    id: 'edge8',
    target: 'node9',
    source: 'node8',
    color: '#00FF00'
  }, {
    id: 'edge9',
    target: 'node10',
    source: 'node9',
    color: '#00FF00',

  }, {
    id: 'edge10',
    target: 'node11',
    source: 'node10',
    color: '#00FF00'
  }, {
    id: 'edge11',
    target: 'node12',
    source: 'node11',
    color: '#00FF00'
  }, {
    id: 'edge12',
    target: 'node6',
    source: 'node11',
    color: '#00FF00'
  }, {
    id: 'edge13',
    target: 'node13',
    source: 'node10',
    color: '#00FF00',
    isrunning: true,
    calc: true,
  }, {
    id: 'edge14',
    target: 'node14',
    source: 'node13',
    color: '#00FF00',
    isrunning: true,
    calc: true,
  }, {
    id: 'edge15',
    target: 'node3',
    source: 'node14',
    // color: '#FF0000',
    calc: true,
  }]
}
module.exports = node